# Generated by Django 5.2.6 on 2025-09-15 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_invitation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormioSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
