# Generated by Django 5.2.6 on 2025-09-16 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_formiosubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formiosubmission',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_formio_submission', to='core.task'),
        ),
    ]
