# Generated by Django 5.2.6 on 2025-09-17 17:23

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import sandwich.core.models.organization
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_encounter_status_alter_invitation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='patient_statuses',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=[], encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (sandwich.core.models.organization.PatientStatus,))),
        ),
    ]
