# Generated by Django 5.2.6 on 2025-09-17 23:37

from django.db import migrations


CREATE_PATIENT_FTS = """
CREATE VIRTUAL TABLE IF NOT EXISTS core_patient_fts USING fts5(
    first_name,
    last_name,
    phn,
    email,
    content='core_patient',
    content_rowid='id'
);

CREATE TRIGGER IF NOT EXISTS core_patient_after_insert
AFTER INSERT ON core_patient
BEGIN
    INSERT INTO core_patient_fts(rowid, first_name, last_name, phn, email)
    VALUES (new.id, new.first_name, new.last_name, new.phn, new.email);
END;

CREATE TRIGGER IF NOT EXISTS core_patient_after_delete
AFTER DELETE ON core_patient
BEGIN
    INSERT INTO core_patient_fts(core_patient_fts, rowid, first_name, last_name, phn, email)
    VALUES ('delete', old.id, old.first_name, old.last_name, old.phn, old.email);
END;

CREATE TRIGGER IF NOT EXISTS core_patient_after_update
AFTER UPDATE ON core_patient
BEGIN
    INSERT INTO core_patient_fts(core_patient_fts, rowid, first_name, last_name, phn, email)
    VALUES ('delete', old.id, old.first_name, old.last_name, old.phn, old.email);
    INSERT INTO core_patient_fts(rowid, first_name, last_name, phn, email)
    VALUES (new.id, new.first_name, new.last_name, new.phn, new.email);
END;

INSERT INTO core_patient_fts(rowid, first_name, last_name, phn, email)
SELECT id, first_name, last_name, phn, email FROM core_patient;
"""

DROP_PATIENT_FTS = """
DROP TRIGGER IF EXISTS core_patient_after_update;
DROP TRIGGER IF EXISTS core_patient_after_delete;
DROP TRIGGER IF EXISTS core_patient_after_insert;
DROP TABLE IF EXISTS core_patient_fts;
"""

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_organization_patient_statuses'),
    ]

    operations = [
        migrations.RunSQL(sql=CREATE_PATIENT_FTS, reverse_sql=DROP_PATIENT_FTS)
    ]
