# Generated by Django 5.2.7 on 2025-10-08 22:45

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='core_Invitation_status_InvitationStatus',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('FAILED_VERIFICATION', 'Failed Verification'), ('FAILED', 'Failed')], default='PENDING', max_length=19),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'FAILED_VERIFICATION', 'FAILED'])), name='core_Invitation_status_InvitationStatus'),
        ),
    ]
