# Generated by Django 5.2.8 on 2025-11-14 09:23

import uuid

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_remove_form_insert_insert_remove_form_update_update_and_more"),
        ("pghistory", "0007_auto_20250421_0444"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthSummary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "summary_type",
                    models.CharField(
                        choices=[("overview", "Overview"), ("focused", "Focused"), ("comprehensive", "Comprehensive")],
                        default="overview",
                        help_text="Type of summary",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField(help_text="The AI-generated summary (markdown or HTML)")),
                (
                    "data_hash",
                    models.CharField(help_text="SHA256 hash of patient data to detect changes", max_length=64),
                ),
                (
                    "source_record_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="IDs of health records included in this summary"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True,
                        help_text="LLM model version used to generate this summary",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0, help_text="Token count for cost tracking")),
                (
                    "generation_time_ms",
                    models.IntegerField(default=0, help_text="Time taken to generate summary in milliseconds"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Whether this is the current summary for this data hash"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Additional metadata")),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient this summary is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_summaries",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Summary",
                "verbose_name_plural": "Health Summaries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthSummaryEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "summary_type",
                    models.CharField(
                        choices=[("overview", "Overview"), ("focused", "Focused"), ("comprehensive", "Comprehensive")],
                        default="overview",
                        help_text="Type of summary",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField(help_text="The AI-generated summary (markdown or HTML)")),
                (
                    "data_hash",
                    models.CharField(help_text="SHA256 hash of patient data to detect changes", max_length=64),
                ),
                (
                    "source_record_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="IDs of health records included in this summary"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True,
                        help_text="LLM model version used to generate this summary",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0, help_text="Token count for cost tracking")),
                (
                    "generation_time_ms",
                    models.IntegerField(default=0, help_text="Time taken to generate summary in milliseconds"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Whether this is the current summary for this data hash"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Additional metadata")),
                (
                    "patient",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="Patient this summary is for",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="core.patient",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="core.healthsummary",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="healthsummary",
            index=models.Index(fields=["patient", "-created_at"], name="core_health_patient_106b29_idx"),
        ),
        migrations.AddIndex(
            model_name="healthsummary",
            index=models.Index(fields=["patient", "data_hash"], name="core_health_patient_14ccf2_idx"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="healthsummary",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_healthsummaryevent" ("content", "created_at", "data_hash", "generation_time_ms", "id", "is_current", "metadata", "model_version", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_record_ids", "summary_type", "tokens_used", "updated_at") VALUES (NEW."content", NEW."created_at", NEW."data_hash", NEW."generation_time_ms", NEW."id", NEW."is_current", NEW."metadata", NEW."model_version", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."source_record_ids", NEW."summary_type", NEW."tokens_used", NEW."updated_at"); RETURN NULL;',
                    hash="6403bea004858b73354f62ebff076d76ffc57e6f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_ab69d",
                    table="core_healthsummary",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="healthsummary",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_healthsummaryevent" ("content", "created_at", "data_hash", "generation_time_ms", "id", "is_current", "metadata", "model_version", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_record_ids", "summary_type", "tokens_used", "updated_at") VALUES (NEW."content", NEW."created_at", NEW."data_hash", NEW."generation_time_ms", NEW."id", NEW."is_current", NEW."metadata", NEW."model_version", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."source_record_ids", NEW."summary_type", NEW."tokens_used", NEW."updated_at"); RETURN NULL;',
                    hash="55b9f47de83de69ae75a17f2f85b95a6c27810f1",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_34f01",
                    table="core_healthsummary",
                    when="AFTER",
                ),
            ),
        ),
    ]
