# Generated by Django 5.2.8 on 2025-11-20 23:42

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_alter_organization_options_summarytemplate_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("planned", "Planned"),
                    ("in-progress", "In Progress"),
                    ("on-hold", "On Hold"),
                    ("discharged", "Discharged"),
                    ("completed", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("discontinued", "Discontinued"),
                    ("entered-in-error", "Entered in Error"),
                    ("unknown", "Unknown"),
                ],
                max_length=16,
            ),
        ),
    ]
